### ISSUE TITLE
vagrant-libvirt no connection to REMOTE Provider after reboot  

### ISSUE THREAD

**Issue by itarch** [vagrant-libvirt/vagrant-libvirt#1172]
### The setup
I run vagrant and vagrant-libvirt in a dedicated VM (named MASTER). Look at the picture below: 
![image](https://user-images.githubusercontent.com/14290953/99826356-8a292200-2b58-11eb-9da5-aade65639b19.png)

Following the instructions in https://github.com/vagrant-libvirt, find below what I've installed in the MASTER VM:
```
#> curl -O https://releases.hashicorp.com/vagrant/2.2.13/vagrant_2.2.13_x86_64.deb
#> sudo apt install ./vagrant_2.2.13_x86_64.deb
#> sudo apt-get build-dep vagrant ruby-libvirt
#> sudo apt-get install qemu libvirt-bin ebtables dnsmasq-base
#> sudo apt-get install libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev
#> vagrant plugin install vagrant-libvirt
```
### Steps to reproduce
Case_1 
After installation of vagrant and vagrant-libvirt (on MASTER VM) I'm able to "up" and "destroy" VMs (e.g. DEV_1 VM) without problems as long as I don't reboot the MASTER VM. When I reboot the MASTER VM I can't control (suspend, destroy, ..) VMS created before nor I can create new ones.  

Case_2
After installation (of vagrant and vagrant-libvirt) and directly reboot the MASTER VM I can't create and destroy VMs.

In both cases I've to perform a fresh installation to be able to use vagrant/vagrant-libvirt again.

### Expected behaviour
survive reboot

### Actual behaviour
After reboot the MASTER VM, it seems vagrant tries to operate within the MASTER VM. It ignores the params added in the Vagrantfile to use the remote Libvirt.

### System configuration
```
me@master:/pr/vm$ cat /etc/os-release
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"

me@host:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
```

**Libvirt version:**
```
me@master:~$ libvirtd --version
libvirtd (libvirt) 4.0.0

me@host:~$ libvirtd --version
libvirtd (libvirt) 4.0.0
```

**Output of `vagrant version; vagrant plugin list`:**
```
me@master:~$ vagrant --version
Vagrant 2.2.13
me@master:~$ vagrant plugin list
vagrant-libvirt (0.3.0, global)
```

**Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`**
The attached vagrant debug log file has been gathered during a destroy process after rebooting the MASTER VM. Before restarting I've created a VM with the Vagrantfile attached in the next section
```
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/5574988/vagrant.log)
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.hostname = "test.local"
  config.vm.define "0.DEV_1" do |dev_1|
      dev_1.vm.network :private_network, ip: "192.168.123.XXX", libvirt__network_name: "vagrant.cicd"
      dev_1.vm.network :public_network,
             :dev => "br0",
             :bridge => "br0",
             :mode => "bridge",
             :type => "bridge",
             :ip => "192.168.1.XXX"
  end
  config.ssh.proxy_command = "/bin/nc -q0 %h %p"
  config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.host = "master.example.com"
        libvirt.connect_via_ssh = true
        libvirt.username = "me"
        libvirt.default_prefix = ""
        libvirt.memory = 2048
        libvirt.cpus = 2
        libvirt.keymap = "de"
  end
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro

**Comment by electrofelix** [comment]
@itarch unset `LIBVIRT_DEFAULT_URI` in your environment before issuing the vagrant up command. I think I messed up in how we order things in determining the correct value to use for connecting by ignoring settings if that env car is set as it is set on ubuntu

**Comment by itarch** [comment]
@electrofelix 
okay, fine, tank you
there is still one Error, which I dont wanted to add here in the initial issue. 
However, although it appears during initial creation it seems not to influence the process/result . 

```
me@master:~/vagrant.test$ LIBVIRT_DEFAULT_URI=
me@master:~/vagrant.test$ vagrant up
Bringing machine '0.TEST' up with 'libvirt' provider...
...
==> 0.TEST: Starting domain.
==> 0.TEST: Error when updating domain settings: undefined method `strip' for nil:NilClass
==> 0.TEST: Waiting for domain to get an IP address...
...
```

Regards

**Comment by electrofelix** [comment]
Pretty sure I know the cause of the next error, just need to expose it with a test, fix it and then release a point release, so hopefully in just a few days.

I'll keep this issue open until I've reworked the behaviour around the env var, thanks for confirming the workaround does work. I suspect you could put a line in the Vagrantfile just before the start of the config to delete the env var with standard ruby to avoid needing to remember to unset.

**Comment by nqb** [comment]
Hello @electrofelix,

Just want to mention that I got "Error when updating domain settings: undefined method `strip' for nil:NilClass" after upgrading to 0.3.0 with Vagrant 2.2.14.

Let me know if I can help.

**Comment by kfix** [comment]
I have the same undefined-method error with the strip on newer vagrants, started after upgrading vagrant from 2.2.5 to 2.2.14.

**Comment by LHozzan** [comment]
Hello.
Same problem here. I attempt to switch from VirtualBox to KVM. Vagrant `v2.2.14`.

**Comment by electrofelix** [comment]
This should be fixed through the landing of #1223 to make the LIBVIRT_DEFAULT_URI a fallback mechanism instead of always being picked up.

Additionally the strip error should be fixed by #1178.

Both should have been in 0.4.0 release.
