### ISSUE TITLE
undefined method `active?'

### ISSUE THREAD

**Issue by insonifi** [vagrant-libvirt/vagrant-libvirt#145]
Hi,
  I need to deploy windows application on KVM. I installed _vagrant-windows_ and _vagrant-libvirt_. Created a base box following instruction from _vagrant-windows_ (installed and configured Windows), then combined _libvirt_ related parts from _vagrant-libvirt_ (made qcow2 image, created metadata.json and packaged the box).

Now, when I'm trying to `vagrant up --provider=libvirt`, I get following errors:

```
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'default' machine. Please report this as a bug:

undefined method `active?' for #<Libvirt::Domain:0x007f4e54a2d330>

/home/dainichi/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/requests/compute/list_domains.rb:64:in `domain_to_attributes'
/home/dainichi/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `block in list_domains'
/home/dainichi/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `map'
/home/dainichi/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `list_domains'
/home/dainichi/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/libvirt/models/compute/servers.rb:13:in `all'
/home/dainichi/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/set_name_of_domain.rb:24:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/call.rb:51:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/home/dainichi/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/connect_libvirt.rb:84:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:147:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
/home/dainichi/.vagrant.d/gems/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:323:in `call'
/home/dainichi/.vagrant.d/gems/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

thanks

**Comment by rshk** [comment]
I can confirm that this solves the issue on Archlinux:

```
# in case it's already installled
vagrant plugin uninstall vagrant-libvirt

sudo mv /opt/vagrant/embedded/lib/libcurl.so{,.backup}
sudo mv /opt/vagrant/embedded/lib/libcurl.so.4{,.backup}
sudo mv /opt/vagrant/embedded/lib/libcurl.so.4.3.0{,.backup}
sudo mv /opt/vagrant/embedded/lib/pkgconfig/libcurl.pc{,.backup}

CONFIGURE_ARGS= vagrant plugin install vagrant-libvirt  44.89s user 4.59s system 46% cpu 1:46.46 total

sudo mv /opt/vagrant/embedded/lib/libcurl.so{.backup,}
sudo mv /opt/vagrant/embedded/lib/libcurl.so.4{.backup,}
sudo mv /opt/vagrant/embedded/lib/libcurl.so.4.3.0{.backup,}
sudo mv /opt/vagrant/embedded/lib/pkgconfig/libcurl.pc{.backup,}
```

**Comment by rbellamy** [comment]
I'm having this same problem on my ArchLinux box, and I installed the plugin using the incantation above, verbatim, as that's what is currently recommended in the wiki: https://wiki.archlinux.org/index.php/Vagrant#vagrant-libvirt. 

No one has mentioned whether or not they're running vagrant as root or as a normal user. I am running as a normal user with authentication turned of via a Polkit rule.

**Comment by rbellamy** [comment]
And I can confirm that the recipe @rshk put up works... I forgot to move the curl files.

**Comment by arndo** [comment]
I'm currently facing the same issue under arch linux, but couldn't resolve it with the solution mentioned by rshk. Anyone can confirm that it works with vagrant 1.7.2?

**Comment by arndo** [comment]
I ended up doing the workaround mentioned [here](https://github.com/adrahon/vagrant-kvm/issues/161#issuecomment-36422567):
+ Install the plugin with ```CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib" vagrant plugin install vagrant-libvirt``` (don't even bother messing with vagrants embedded curl libs)
+ Install ruby-libvirt from [AUR](https://aur.archlinux.org/packages/ruby-libvirt/)
+ Copy the files from ```/usr/lib/ruby/gems/2.2.0/gems/ruby-libvirt``` into ```~/vagrant.d/gems/gems```
+ ```vagrant init mylibvirtbox && vagrant up --provider libvirt```
+ Instant happiness :grinning:

**Comment by slackcub** [comment]
I'm still seeing this issue, in spite of installing ruby-libvirt from AUR and running 'cp -av /usr/lib/ruby/gems/2.2.0/gems/ruby-libvirt-0.5.2/* ~/vagrant.d/gems/gems/'.  I also had moved the curl libraries during installation of vagrant-libvirt. 

I'm still getting the following error: 

```
[slackcub@Sisko archTest]$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
/home/slackcub/.vagrant.d/gems/gems/fog-1.29.0/lib/fog/libvirt/requests/compute/list_domains.rb:64:in `domain_to_attributes': undefined method `active?' for #<Libvirt::Domain:0x00000002c9d0b8> (NoMethodError)
	from /home/slackcub/.vagrant.d/gems/gems/fog-1.29.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `block in list_domains'
	from /home/slackcub/.vagrant.d/gems/gems/fog-1.29.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `map'
	from /home/slackcub/.vagrant.d/gems/gems/fog-1.29.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `list_domains'
	from /home/slackcub/.vagrant.d/gems/gems/fog-1.29.0/lib/fog/libvirt/models/compute/servers.rb:11:in `all'
	from /home/slackcub/.vagrant.d/gems/gems/vagrant-libvirt-0.0.26/lib/vagrant-libvirt/action/set_name_of_domain.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/slackcub/.vagrant.d/gems/gems/vagrant-libvirt-0.0.26/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
[slackcub@Sisko archTest]$ 
```

Versioning info:

```
[slackcub@Sisko archTest]$ vagrant --version
Vagrant 1.7.2
[slackcub@Sisko archTest]$ vagrant plugin list
vagrant-libvirt (0.0.26)
vagrant-mutate (0.3.2)
[slackcub@Sisko archTest]$ 
```

and installed packages:

```
[slackcub@Sisko archTest]$ pacman -Q | grep -P 'libvirt|vagrant'
libvirt 1.2.15-1
libvirt-glib 0.2.0-1
libvirt-python 1.2.15-1
ruby-libvirt 0.5.2-1
vagrant 1.7.2-2
[slackcub@Sisko archTest]$ 
```

**Comment by mmlb** [comment]
@arndo tried you work around (symlink instead of cp) and it works.

**Comment by infernix** [comment]
I'm flagging this as an upstream bug; if anyone could please report complete steps to replicate the issue under current vagrant (1.8.1+) and vagrant-libvirt (0.0.33) for any host OS, I will attempt to determine whether if we need to file a bug elsewhere.

**Comment by cygnusb** [comment]
I have the same issue here, running OSX 10.11 with vagrant 1.8.5, vagrant-libvirt 0.0.33 and with patched ruby-libvirt (see #497).

/Users/szczepan/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_domains.rb:64:in `domain_to_attributes': undefined method `active?' for #<Libvirt::Domain:0x00000100e01dd8> (NoMethodError)
	from /Users/szczepan/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `block in list_domains'
	from /Users/szczepan/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `map'
	from /Users/szczepan/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `list_domains'
	from /Users/szczepan/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/models/compute/servers.rb:11:in `all'
	from /Users/szczepan/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/set_name_of_domain.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:225:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:200:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:561:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:186:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:186:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by infernix** [comment]
Please retest this against current master which updates fog-libvirt and ruby-libvirt.

You can `git clone` the repo and do a `gem build vagrant-libvirt.gemspec` which generates a `.gem` that can be installed with `vagrant plugin install /path/to/gem`

**Comment by petRUShka** [comment]
Right now on archlinux:

```
✗ vagrant up --provider libvirt
/opt/vagrant/embedded/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/requests/compute/list_domains.rb:76:in `domain_to_attributes': undefined method `active?' for #<Libvirt::Domain:0x00000001da1dc0> (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `block in list_domains'
	from /opt/vagrant/embedded/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `map'
	from /opt/vagrant/embedded/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `list_domains'
	from /opt/vagrant/embedded/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/models/compute/servers.rb:15:in `get'
	from /opt/vagrant/embedded/gems/gems/vagrant-libvirt-0.0.37/lib/vagrant-libvirt/driver.rb:52:in `get_domain'
	from /opt/vagrant/embedded/gems/gems/vagrant-libvirt-0.0.37/lib/vagrant-libvirt/driver.rb:66:in `created?'
	from /opt/vagrant/embedded/gems/gems/vagrant-libvirt-0.0.37/lib/vagrant-libvirt/provider.rb:101:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/machine.rb:506:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/machine.rb:145:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/vagrantfile.rb:79:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/vagrantfile.rb:79:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/environment.rb:669:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/plugin/v2/command.rb:201:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/plugin/v2/command.rb:183:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/plugins/commands/up/command.rb:131:in `install_providers'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/plugins/commands/up/command.rb:85:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/bin/vagrant:127:in `<main>'
```

**Comment by electrofelix** [comment]
Going through the old issues, I haven't seen this occur for some time.

It also appears that it must be an issue with detecting the header files. To debug if it's still happening (may still occur for Macs) it will require a detailed set of steps to try and reproduce:
* distro and release
* libvirt version
* vagrant version
* ruby-libvirt gem installed under ~/.vagrant.d/gems/<version>/gems/

Going to let the no-response bot close this in about 30 days if no further details are possible.
