### ISSUE TITLE
Error when updating domain settings: undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by abbbi** [vagrant-libvirt/vagrant-libvirt#1176]
After updating to the latest vagrant-libvirt version im seeing this one:
Vagrant 2.2.9

> INFO interface: info: ==> default: Starting domain.
> ==> default: Starting domain.
> INFO interface: error: Error when updating domain settings: undefined method `strip' for nil:NilClass
> INFO interface: error: ==> default: Error when updating domain settings: undefined method `strip' for nil:NilClass
> ==> default: Error when updating domain settings: undefined method `strip' for nil:NilClass

it seems to work without problems but might be worth looking into.
--debug doesnt show anything usefull though

**Comment by zakame** [comment]
Can confirm here too, looks like a regression from https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1167

```
$ vagrant up
...
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Error when updating domain settings: undefined method `strip' for nil:NilClass
==> default: Waiting for domain to get an IP address...
...
$ vagrant status
Current machine states:

default                   running (libvirt)

...
```

**Comment by electrofelix** [comment]
@abbbi @zakame I think this is now fixed, but I found that for some reason I couldn't reproduce the behaviour consistently across my different machines, so might be worth if someone else could verify.

**Comment by zakame** [comment]
@electrofelix thanks, the warning is now gone for me :tada:

**Comment by electrofelix** [comment]
@zakame good to know, thanks for confirming.

**Comment by maciej-przezdziecki** [comment]
@electrofelix Seems that issue is still ongoing

[root@test ~]# vagrant plugin list
vagrant-libvirt (0.3.0, global)

==> osX:  -- INPUT:             type=mouse, bus=ps2
==> osX: Creating shared folders metadata...
==> osX: Starting domain.
==> osX: Error when updating domain settings: undefined method `strip' for nil:NilClass
==> osX: Waiting for domain to get an IP address...

**Comment by electrofelix** [comment]
@maciej-przezdziecki you'll need to install from master as the fix isn't yet in a release.
